language: java
sudo: false
install:
    - mkdir lib
    - wget "https://github.com/mttkay/signpost/releases/download/1.2.1.2/signpost-core-1.2.1.2.jar" -O lib/signpost.jar
    - wget "https://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar" -O lib/junit.jar
    - wget "https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" -O lib/hamcrest.jar
    - curl "http://xenia.sote.hu/ftp/mirrors/www.apache.org//commons/codec/binaries/commons-codec-1.11-bin.tar.gz" | tar -xz "commons-codec-1.11/commons-codec-1.11.jar"
    - mv commons-codec-1.11/commons-codec-1.11.jar lib/commons-codec.jar
    - ln OAuthConfig.sample.java src/burp/OAuthConfig.java

jdk:
    - oraclejdk8
    - oraclejdk9
    - openjdk7
    - openjdk8
os:
    - linux
